### ISSUE TITLE
Can you please publish the source code of Metafor?

### ISSUE THREAD

**Issue by QiangF** [rboman/rboman.github.io#1]
Dear Prof. Boman,

The open source world still lacks a finite element package capable of solving large plastic deformation. Are you interested of filling the void by releasing the source code for Metafor?

Regards.

**Comment by rboman** [comment]
Hello,

Thanks for your message. 

I would be very happy to release the source code of Metafor. Unfortunately the whole code belongs to my employer (the university of liège) and they do not want to release it. The university recieves money each time we sell a license. I think this is the main reason. The situation is thus very complicated and sad.

Anyway I'm still trying to convince them and I hope they will understand someday that open source is the right way to do science.
